//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAVConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAVConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap alt2 {
            get {
                object obj = ResourceManager.GetObject("alt2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asi_needle {
            get {
                object obj = ResourceManager.GetObject("asi_needle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attitude1 {
            get {
                object obj = ResourceManager.GetObject("attitude1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attitude2 {
            get {
                object obj = ResourceManager.GetObject("attitude2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attitude3 {
            get {
                object obj = ResourceManager.GetObject("attitude3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attitude5 {
            get {
                object obj = ResourceManager.GetObject("attitude5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusAutopilotConfig&gt;&lt;servo_ctrl&gt;&lt;min&gt;1000&lt;/min&gt;&lt;max&gt;2000&lt;/max&gt;&lt;center&gt;1500&lt;/center&gt;&lt;reverse&gt;0&lt;/reverse&gt;&lt;/servo_ctrl&gt;&lt;servo_ail&gt;&lt;min&gt;1000&lt;/min&gt;&lt;max&gt;2000&lt;/max&gt;&lt;center&gt;1500&lt;/center&gt;&lt;reverse&gt;0&lt;/reverse&gt;&lt;/servo_ail&gt;&lt;servo_ele&gt;&lt;min&gt;1000&lt;/min&gt;&lt;max&gt;2000&lt;/max&gt;&lt;center&gt;1500&lt;/center&gt;&lt;reverse&gt;0&lt;/reverse&gt;&lt;/servo_ele&gt;&lt;servo_thr&gt;&lt;min&gt;1000&lt;/min&gt;&lt;max&gt;2000&lt;/max&gt;&lt;center&gt;1500&lt;/center&gt;&lt;reverse&gt;0&lt;/reverse&gt;&lt;/servo_thr&gt;&lt;servo_tail&gt;&lt;min&gt;1000&lt;/min&gt;&lt;max&gt;2000&lt;/max&gt;&lt;center&gt;1500&lt;/center&gt;&lt;reverse&gt;0&lt;/reverse&gt;&lt;/servo_tail&gt;&lt;AutopilotMode&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string autopilot_config {
            get {
                return ResourceManager.GetString("autopilot_config", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copilot {
            get {
                object obj = ResourceManager.GetObject("Copilot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap default_texture {
            get {
                object obj = ResourceManager.GetObject("default_texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusScreenConfig&gt;&lt;Altimetro&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;7&lt;/fila&gt;&lt;col&gt;2&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Altimetro&gt;&lt;Autopilot&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;2&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Autopilot&gt;&lt;Bearing&gt;&lt;tipo&gt;3&lt;/tipo&gt;&lt;fila&gt;-3&lt;/fila&gt;&lt;col&gt;13&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Bearing&gt;&lt;Compas&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;0&lt;/col&gt;&lt;param&gt;5&lt;/param&gt;&lt;/Compas&gt;&lt;Dist_Home&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;-1&lt;/fila&gt;&lt;col&gt;18&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Home&gt;&lt;Dist_Wpt&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;-1&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Wpt&gt;&lt;Hora&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fi [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Failsafe {
            get {
                return ResourceManager.GetString("Failsafe", resourceCulture);
            }
        }
        
        internal static byte[] firmware {
            get {
                object obj = ResourceManager.GetObject("firmware", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fw_anttrack {
            get {
                object obj = ResourceManager.GetObject("fw_anttrack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fw_uplink {
            get {
                object obj = ResourceManager.GetObject("fw_uplink", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdg1 {
            get {
                object obj = ResourceManager.GetObject("hdg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hdg2 {
            get {
                object obj = ResourceManager.GetObject("hdg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusScreenConfig&gt;&lt;Altimetro&gt;&lt;tipo&gt;2&lt;/tipo&gt;&lt;fila&gt;5&lt;/fila&gt;&lt;col&gt;0&lt;/col&gt;&lt;param&gt;6&lt;/param&gt;&lt;/Altimetro&gt;&lt;Autopilot&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;11&lt;/fila&gt;&lt;col&gt;10&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Autopilot&gt;&lt;Bearing&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;-2&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Bearing&gt;&lt;Compas&gt;&lt;tipo&gt;2&lt;/tipo&gt;&lt;fila&gt;2&lt;/fila&gt;&lt;col&gt;8&lt;/col&gt;&lt;param&gt;12&lt;/param&gt;&lt;/Compas&gt;&lt;Dist_Home&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Home&gt;&lt;Dist_Wpt&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Wpt&gt;&lt;Hora&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fi [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HUD1 {
            get {
                return ResourceManager.GetString("HUD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusScreenConfig&gt;&lt;Altimetro&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;23&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Altimetro&gt;&lt;Autopilot&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;5&lt;/fila&gt;&lt;col&gt;10&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Autopilot&gt;&lt;Bearing&gt;&lt;tipo&gt;2&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;13&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Bearing&gt;&lt;Compas&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;16&lt;/col&gt;&lt;param&gt;5&lt;/param&gt;&lt;/Compas&gt;&lt;Dist_Home&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;-1&lt;/fila&gt;&lt;col&gt;18&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Home&gt;&lt;Dist_Wpt&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;5&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Wpt&gt;&lt;Hora&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fil [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HUD2 {
            get {
                return ResourceManager.GetString("HUD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusScreenConfig&gt;&lt;Altimetro&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;7&lt;/fila&gt;&lt;col&gt;2&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Altimetro&gt;&lt;Autopilot&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;3&lt;/fila&gt;&lt;col&gt;10&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Autopilot&gt;&lt;Bearing&gt;&lt;tipo&gt;3&lt;/tipo&gt;&lt;fila&gt;-3&lt;/fila&gt;&lt;col&gt;13&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Bearing&gt;&lt;Compas&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;0&lt;/fila&gt;&lt;col&gt;0&lt;/col&gt;&lt;param&gt;5&lt;/param&gt;&lt;/Compas&gt;&lt;Dist_Home&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;-1&lt;/fila&gt;&lt;col&gt;18&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Home&gt;&lt;Dist_Wpt&gt;&lt;tipo&gt;1&lt;/tipo&gt;&lt;fila&gt;-1&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Wpt&gt;&lt;Hora&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fi [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HUD3 {
            get {
                return ResourceManager.GetString("HUD3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ICO_dossier_home_ico_64x64 {
            get {
                object obj = ResourceManager.GetObject("ICO_dossier_home_ico_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Ikarus {
            get {
                object obj = ResourceManager.GetObject("Ikarus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IkarusLogo {
            get {
                object obj = ResourceManager.GetObject("IkarusLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Know_azul {
            get {
                object obj = ResourceManager.GetObject("Know_azul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Know_rojo {
            get {
                object obj = ResourceManager.GetObject("Know_rojo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap madr_misc1 {
            get {
                object obj = ResourceManager.GetObject("madr_misc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap misc2 {
            get {
                object obj = ResourceManager.GetObject("misc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap misc3 {
            get {
                object obj = ResourceManager.GetObject("misc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusBasicConfig&gt;&lt;videoPAL&gt;1&lt;/videoPAL&gt;&lt;offsetX&gt;41&lt;/offsetX&gt;&lt;offsetY&gt;24&lt;/offsetY&gt;&lt;cellsBatt1&gt;3&lt;/cellsBatt1&gt;&lt;cellsBatt2&gt;3&lt;/cellsBatt2&gt;&lt;total_mAh&gt;2200&lt;/total_mAh&gt;&lt;cellAlarm&gt;3&lt;/cellAlarm&gt;&lt;distanceAlarm&gt;1000&lt;/distanceAlarm&gt;&lt;altitudeAlarm&gt;100&lt;/altitudeAlarm&gt;&lt;lowSpeedAlarm&gt;20&lt;/lowSpeedAlarm&gt;&lt;HomeLon&gt;-5.26264&lt;/HomeLon&gt;&lt;HomeLat&gt;37.668&lt;/HomeLat&gt;&lt;HomeAltitude&gt;128.1&lt;/HomeAltitude&gt;&lt;WptRange&gt;50&lt;/WptRange&gt;&lt;DefaultHUD&gt;1&lt;/DefaultHUD&gt;&lt;TelemetryMode&gt;1&lt;/TelemetryMode&gt;&lt;ControlProportional&gt;1&lt;/ControlProportional&gt;&lt;AbsoluteAlti [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string osd_config {
            get {
                return ResourceManager.GetString("osd_config", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap plane1 {
            get {
                object obj = ResourceManager.GetObject("plane1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plane2 {
            get {
                object obj = ResourceManager.GetObject("plane2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plane3 {
            get {
                object obj = ResourceManager.GetObject("plane3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;IkarusScreenConfig&gt;&lt;Altimetro&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;14&lt;/fila&gt;&lt;col&gt;7&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Altimetro&gt;&lt;Autopilot&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;13&lt;/fila&gt;&lt;col&gt;11&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Autopilot&gt;&lt;Bearing&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;2&lt;/fila&gt;&lt;col&gt;13&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Bearing&gt;&lt;Compas&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;1&lt;/fila&gt;&lt;col&gt;10&lt;/col&gt;&lt;param&gt;8&lt;/param&gt;&lt;/Compas&gt;&lt;Dist_Home&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;14&lt;/fila&gt;&lt;col&gt;13&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Home&gt;&lt;Dist_Wpt&gt;&lt;tipo&gt;0&lt;/tipo&gt;&lt;fila&gt;14&lt;/fila&gt;&lt;col&gt;19&lt;/col&gt;&lt;param&gt;0&lt;/param&gt;&lt;/Dist_Wpt&gt;&lt;Hora&gt;&lt;tipo&gt;2&lt;/tipo&gt;&lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sight_icon_2 {
            get {
                object obj = ResourceManager.GetObject("sight_icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sphere_Green {
            get {
                object obj = ResourceManager.GetObject("Sphere_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sphere_Red {
            get {
                object obj = ResourceManager.GetObject("Sphere_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap velocidad {
            get {
                object obj = ResourceManager.GetObject("velocidad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video_red {
            get {
                object obj = ResourceManager.GetObject("video_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vsi1 {
            get {
                object obj = ResourceManager.GetObject("vsi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
